product_list:
  output_dir:
    /mnt/output/
  subscribe_topics:
    - /dataset/seviri_hrit
  publish_topic: /image/seviri_hrit
  reader: seviri_l1b_hrit
  fname_pattern:
    "{start_time:%Y%m%d_%H%M}_{platform_name}_{areaname}_{productname}.{format}"
  sunzen_check_lon: 5.0
  sunzen_check_lat: 56.0
  # Delay composite generation until resampling is done.  This is
  # faster when many products share the same channels
  delay_composites: True

  areas:
    euro4:

      # Add a priority. Not relevant for one area, but just to show the option
      priority: 1
      areaname: euro4
      # Search radius for resampling
      radius_of_influence: 20000
      # Resampling method
      resampler: nearest

      products:
        overview:
          productname: overview
          formats:
            - format: tif
              writer: geotiff
          sunzen_maximum_angle: 90.0
        #day_microphysics:
        #  productname: day_microphysics
        airmass:
          productname: airmass
          formats:
            - format: tif
              writer: geotiff
        natural_color:
          productname: natural_color
          formats:
            - format: tif
              writer: geotiff
          sunzen_maximum_angle: 90.0
        night_fog:
          productname: night_fog
          formats:
            - format: tif
              writer: geotiff
          sunzen_minimum_angle: 90.0

workers:
  - fun: !!python/name:trollflow2.plugins.create_scene
  - fun: !!python/name:trollflow2.plugins.sza_check
  - fun: !!python/name:trollflow2.plugins.load_composites
  - fun: !!python/name:trollflow2.plugins.resample
  - fun: !!python/name:trollflow2.plugins.save_datasets
  - fun: !!python/object:trollflow2.plugins.FilePublisher {}
